---
- name: My Babys Got LED Test and Programming Rig for a Raspberry Pi
  hosts: test-rig
  vars:
    pi_name: mbgl-tap
  remote_user: pi
  become: yes
  become_method: sudo
  # Include whichever roles make sense here
  roles:
    - nm-wireless
  #  - base-nodered
  #  - ssh-tunnel

  pre_tasks:
    - name: Update apt
      apt: upgrade=dist update_cache=yes
      become: true

  handlers:
  - name: restart udev
    service: name=udev state=restarted
  - name: restart Pi
    reboot:

  tasks:
  - name: Change Pis name
    hostname: name="{{ pi_name }}"
  - name: Update hosts file too
    replace: dest=/etc/hosts regexp='raspberrypi' replace="{{ pi_name }}"
  - name: Install git
    apt: name=git state=present
  - name: Install vim
    apt: name=vim state=present
  - name: Install python3
    apt: name=python3 state=present
  - name: Install python3-pip
    apt: name=python3-pip state=present
  - name: Make Python3 the default
    alternatives:
      name: python
      path: /usr/bin/python3
      link: /usr/bin/python
  - name: Install platformio
    pip: name=platformio
  - name: Install udev rules for platformio
    get_url:
      url: https://raw.githubusercontent.com/platformio/platformio-core/develop/scripts/99-platformio-udev.rules
      dest: /etc/udev/rules.d/99-platformio-udev.rules
    notify:
      - restart udev
  - name: Disable the console on the built-in serial port
    lineinfile:
      path: '/boot/cmdline.txt'
      regexp: '^(.*)console=serial0,115200(.*)$'
      line: '\1\2'
      backrefs: yes
    notify:
      - restart Pi
  - name: Clone the WLED repo
    ansible.builtin.git:
      repo: 'https://github.com/mcqn/WLED.git'
      dest: /home/pi/WLED
    become: no
